library(car)
library(dhglm)
library(dplyr)
library(effects)
library(ggplot2)
library(glmm)
library(gridExtra)
library(lme4)
library(lmerTest)
library(mcmc)
library(plotly)
library(reshape2)
#setwd("C:/Users/zebadiah/NDSU Dropbox/Dropbox/Geum triflorum/Master_Datasheets")
##ASUS
setwd("C:/Users/zippy/Dropbox/Geum triflorum/Master_Datasheets")
#set colors   #Prairie   #GL ALvar  #MB Alvar
col.esa <- c("#18563E", "#82BE42", "#FFC423")
