library(car)
library(dhglm)
library(dplyr)
library(effects)
library(ggplot2)
library(glmm)
library(gridExtra)
library(lme4)
library(lmerTest)
library(mcmc)
library(plotly)
library(reshape2)
setwd("C:/Users/zebadiah/NDSU Dropbox/Dropbox/Geum triflorum/Master_Datasheets")